### ISSUE TITLE
Order ID xxx for app xxx has already been used by transaction xxx.

### ISSUE THREAD

**Issue by GameStartStudio** [LiveOrDevTrying/Steam.Net#1]
Hi, very nice library. But I encountered a very strange problem in the process of using, the first time "InitTxn" can be successful, the trading order interface pops up. But the second time both returned "Order ID xxx for app xxx has already been used by transaction xxx.", I hope to get your help. Best wishes~

**Comment by LiveOrDevTrying** [comment]
Thank you for your comment - give me a few minutes and I'll look into what is happening.

**Comment by LiveOrDevTrying** [comment]
Hi @qq60665 ,

I found this in the Steam Micro-Tx guide:
**Order ID** - A unique 64-bit number that you assign for this purchase. This number is your key to the transaction. It is used to reference the transaction within the Steam system.

So for order id, you need to use a unique number each time you call PostSteamInitPurchaseAsync. Every call will need a new id. For my setup, I am using a sql server and use the next identity int represents the orderId.

I hope this helps - I'll be adding documentation to this library shortly, please let me know if you run into any more issues. Thanks,
Rob

**Comment by GameStartStudio** [comment]
@LiveOrDevTrying thank you very much for your help and reply. Sure enough, there was a problem with the "Order ID" I generated. Haha, I have solved all my problems now
